export const metadata = {
    title: 'Blog List',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (

        <>
            {children}
        </>


    )
}
